stage: stage_c
max_steps: 50000
batch_size: 4
optimizer:
  name: adamw
  lr: 1.0e-4
lr_schedule:
  name: cosine
  warmup_steps: 2000
solids:
  weight: 1.0
  tv_weight: 0.1
  sparsity_weight: 0.05
gases:
  weight: 1.0
  dice_weight: 1.0
  column_weight: 0.5
precision: bf16
